batch_size: 4
iters: 160000

model:
  type: UNet
  num_classes: 2
  use_deconv: False
  pretrained: Null

train_dataset:
  type: Dataset
  num_classes: 2
  dataset_root: data/voc/VOCdevkit/VOCleather/
  train_path: data/voc/VOCdevkit/VOCleather/train051.txt
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  num_classes: 2
  dataset_root: data/voc/VOCdevkit/VOCleather/
  val_path: data/voc/VOCdevkit/VOCleather/val051.txt
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0.0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
